# Generated by Django 5.1.7 on 2025-06-09 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
