# Generated by Django 5.1.7 on 2025-09-09 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='QRPresence', max_length=200)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site_logos/')),
                ('academic_year', models.CharField(default='2023/2024', max_length=20)),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Summer Semester')], default='1', max_length=20)),
                ('attendance_threshold', models.PositiveIntegerField(default=75, help_text='Minimum attendance percentage required', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('qr_code_expiry', models.PositiveIntegerField(default=15, help_text='QR code validity in minutes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
