# Generated by Django 5.1.7 on 2025-09-03 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at', 'code']},
        ),
        migrations.AlterModelOptions(
            name='lecturer',
            options={'ordering': ['name', 'lecturer_id']},
        ),
        migrations.AlterModelOptions(
            name='qrcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id']},
        ),
        migrations.AlterModelOptions(
            name='studentcourseenrollment',
            options={'ordering': ['-enrolled_at']},
        ),
    ]
