# Generated by Django 5.1.7 on 2025-04-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_lecturer_user_student_user'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='session',
            name='session_id',
            field=models.CharField(default=12345678, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=20),
        ),
    ]
