# Generated by Django 5.1.7 on 2025-04-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_session_wifi_ssid_session_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='wifi_ssid',
        ),
    ]
