# Generated by Django 5.1.7 on 2025-07-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance_latitude_attendance_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='program',
        ),
    ]
