# Generated by Django 5.1.7 on 2025-07-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_rename_course_student_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
