# Generated by Django 5.1.7 on 2025-07-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_lecturer_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-check_in_time']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-timestamp']},
        ),
    ]
