# Generated by Django 5.1.7 on 2025-07-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_session_qr_code_course_session_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='qr_code',
        ),
    ]
